/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ay.isystem.views.panels.products;

import com.ay.isystem.db.DBM;
import com.ay.isystem.models.EntityBeans.MasterList;
import com.ay.isystem.models.EntityBeans.Products;
import com.ay.isystem.models.EntityBeans.ProductsVehicles;
import com.ay.isystem.models.EntityBeans.Vehicle;
import com.ay.isystem.models.Response;
import com.ay.isystem.utililty.Global;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Adeel rana
 */
public class AddProductsDialog extends javax.swing.JDialog {

    DefaultListModel<Vehicle> dlm;
    private Products product;
    private boolean isEdit;
    private double oldQty;

    /**
     * Creates new form AddProductsDialog
     *
     * @param parent
     * @param modal
     */
    public AddProductsDialog(java.awt.Frame parent, boolean modal, Products product) {
        super(parent, modal);
        initComponents();
        isEdit = true;
        this.product = product;

        AutoCompleteDecorator.decorate(masterCombo);
        AutoCompleteDecorator.decorate(vehiclesCombo);
        Global.addListToCombo(masterCombo, (ArrayList<MasterList>) Global.CONTROLLER.fetch("masterList").getResponseObject());
        Global.addListToCombo(vehiclesCombo, (ArrayList<Vehicle>) Global.CONTROLLER.fetch("vehicle").getResponseObject());
        dlm = new DefaultListModel<>();
        jList1.setModel(dlm);

        System.out.println("" + DBM.getSingleRecordById(MasterList.class, product.getTypeId()));
        masterCombo.setSelectedItem(DBM.getSingleRecordById(MasterList.class, product.getTypeId()));
        jTextDescription.setText(product.getName());
        this.oldQty = this.product.getOpeningQty();
        jTextQty.setText(this.product.getOpeningQty() + "");
        jTextOpening.setText(this.product.getOpeningPrice() + "");
        jTextDesc.setText(this.product.getRemarks());

        for (ProductsVehicles v : product.getVehiclesList()) {
            Global.addToList(dlm, v.getVehicle());
        }

    }

    /**
     * Creates new form AddProductsDialog
     *
     * @param parent
     * @param modal
     */
    public AddProductsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isEdit = false;
        AutoCompleteDecorator.decorate(masterCombo);
        AutoCompleteDecorator.decorate(vehiclesCombo);
        Global.addListToCombo(masterCombo, (ArrayList<MasterList>) Global.CONTROLLER.fetch("masterList").getResponseObject());
        Global.addListToCombo(vehiclesCombo, (ArrayList<Vehicle>) Global.CONTROLLER.fetch("vehicle").getResponseObject());
        dlm = new DefaultListModel<>();
        jList1.setModel(dlm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextQty = new javax.swing.JTextField();
        jTextDescription = new javax.swing.JTextField();
        masterCombo = new javax.swing.JComboBox();
        jTextOpening = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDesc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        vehiclesCombo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Products");

        jLabel2.setText("Code");

        jLabel3.setText("Description");

        jLabel4.setText("Opening Quantity");

        jLabel5.setText("Unit Price");

        jLabel6.setText("Remarks");

        jTextDescription.setEditable(false);

        masterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterComboActionPerformed(evt);
            }
        });

        jTextDesc.setColumns(20);
        jTextDesc.setRows(5);
        jScrollPane1.setViewportView(jTextDesc);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        jLabel7.setText("Vehicles");

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextOpening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(masterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(vehiclesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jTextDescription, jTextOpening, jTextQty, masterCombo, vehiclesCombo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextOpening, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextDescription, jTextOpening, jTextQty, masterCombo, vehiclesCombo});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (vehiclesCombo.getSelectedItem() != null) {
            Global.addToList(dlm, vehiclesCombo.getSelectedItem());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jList1.getSelectedIndex() != -1) {
            Global.removeFromList(dlm, jList1.getSelectedValue());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void masterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterComboActionPerformed
        if (null != masterCombo.getSelectedItem()) {
            jTextDescription.setText(((MasterList) masterCombo.getSelectedItem()).getProductDescription());
        }
    }//GEN-LAST:event_masterComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (isEdit) {
                MasterList item = (MasterList) masterCombo.getSelectedItem();
                product.setName(item.getProductDescription());
                product.setCode(item.getProductCode());
                product.setTypeId(item.getId());

                product.setQuantity(Double.parseDouble(jTextQty.getText()));
                product.setPrice(Double.parseDouble(jTextOpening.getText()));

                jTextQty.getText();
                jTextOpening.getText();

                DBM.updateRecords(Products.class, product);
                HashMap hm = new HashMap();
                hm.put("productId", product.getId());
                DBM.deleteRecordsBy(ProductsVehicles.class, hm);
                if (dlm.size() > 0) {
                    for (int i = 0; i < dlm.size(); i++) {
                        Vehicle v = dlm.getElementAt(i);
                        ProductsVehicles pv = new ProductsVehicles(null, product.getId(), v.getId());
                        Global.CONTROLLER.insertRecord(pv, "ProductsVehicles");
                    }
                }
            } else {
                MasterList item = (MasterList) masterCombo.getSelectedItem();
                Products p = new Products(null, item.getProductDescription(), item.getProductCode(), item.getId(), 0, 0, Double.parseDouble(jTextQty.getText()), Double.parseDouble(jTextOpening.getText()), 0, 0, Double.parseDouble(jTextQty.getText()), Double.parseDouble(jTextOpening.getText()));
                Response insertRecord = Global.CONTROLLER.insertRecord(p, "Products");
                if (insertRecord.isError()) {
                    Global.CONTROLLER.deleteRecord(p.getId(), Products.class);
                    JOptionPane.showMessageDialog(this, insertRecord.getErrorMsg());
                } else {
                    if (dlm.size() > 0) {
                        for (int i = 0; i < dlm.size(); i++) {
                            Vehicle v = dlm.getElementAt(i);
                            ProductsVehicles pv = new ProductsVehicles(null, p.getId(), v.getId());
                            Global.CONTROLLER.insertRecord(pv, "ProductsVehicles");
                        }

                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextDesc;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTextField jTextOpening;
    private javax.swing.JTextField jTextQty;
    private javax.swing.JComboBox masterCombo;
    private javax.swing.JComboBox vehiclesCombo;
    // End of variables declaration//GEN-END:variables
}
