/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ay.isystem.views.panels.vendors;

import com.ay.isystem.db.DBM;
import com.ay.isystem.models.EntityBeans.Account;
import com.ay.isystem.models.EntityBeans.PayableReceiveable;
import com.ay.isystem.models.EntityBeans.Vendors;
import com.ay.isystem.models.Response;
import com.ay.isystem.utililty.Global;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Adeel rana
 */
public class AddPayablesPanel extends javax.swing.JPanel {

    String title;

    /**
     * Creates new form AddPayablesPanel
     */
    private AddPayablesPanel() {
        initComponents();
    }

    public AddPayablesPanel(String title) {
        initComponents();
        this.title = title;
        jLabelTitle.setText("Add " + title);
        loadData(title);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCheque = new javax.swing.JTextField();
        etRemarks = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        comboVendorNameAuto = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboPaymentMethod = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        etAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        currentBalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Remarks");

        jLabel5.setText("Cheque No");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Vendor Name");

        comboVendorNameAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVendorNameAutoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Vendor Balance");

        comboPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaymentMethodActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Amount ");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Account ");

        currentBalance.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Date");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Payables");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 67, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboPaymentMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentBalance)
                                    .addComponent(comboVendorNameAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCheque)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboPaymentMethod, comboVendorNameAuto, currentBalance, etAmount, etRemarks, jXDatePicker1, txtCheque});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboVendorNameAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboPaymentMethod, comboVendorNameAuto, currentBalance, etAmount, etRemarks, jXDatePicker1, txtCheque});

    }// </editor-fold>//GEN-END:initComponents

    private void comboVendorNameAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVendorNameAutoActionPerformed
//        //        DefaultComboBoxModel dfComboModelVendor = (DefaultComboBoxModel) this.comboVendorNameAuto.getModel();
        Vendors vendorBean = (Vendors) this.comboVendorNameAuto.getSelectedItem();
        currentBalance.setText("" + vendorBean.getCurrentBalance());
    }//GEN-LAST:event_comboVendorNameAutoActionPerformed

    private void comboPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaymentMethodActionPerformed
//        DefaultComboBoxModel dfComboModel = (DefaultComboBoxModel) this.comboPaymentMethod.getModel();
        String item = comboPaymentMethod.getSelectedItem().toString();
        if (item.equals("Counter Cash")) {
            jLabel5.setVisible(false);
            txtCheque.setVisible(false);
            txtCheque.setText("");
        } else {
            jLabel5.setVisible(true);
            txtCheque.setVisible(true);
        }
    }//GEN-LAST:event_comboPaymentMethodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Global.addPanel(new PayablePanel(title), (JPanel) this.getParent());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            PayableReceiveable tran = new PayableReceiveable();
            tran.setDate(jXDatePicker1.getDate().getTime());
            tran.setAccountId(((Account) comboPaymentMethod.getSelectedItem()).getId());
            tran.setPartyId(((Vendors) comboVendorNameAuto.getSelectedItem()).getId());
            tran.setAmount(Double.parseDouble(etAmount.getText()));
            tran.setChequeNo(txtCheque.getText());
            tran.setParty((Vendors) comboVendorNameAuto.getSelectedItem());
            tran.setPartyType(title);
            tran.setRemarks(etRemarks.getText());

            Response insertRecord = Global.CONTROLLER.addPayableReceiveable(tran);
            if (insertRecord.isError()) {
                JOptionPane.showMessageDialog(this, insertRecord.getErrorMsg());
            } else {
                Global.addPanel(new PayablePanel(title), (JPanel) this.getParent());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboPaymentMethod;
    private javax.swing.JComboBox comboVendorNameAuto;
    private javax.swing.JTextField currentBalance;
    private javax.swing.JTextField etAmount;
    private javax.swing.JTextField etRemarks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField txtCheque;
    // End of variables declaration//GEN-END:variables

    private void loadData(String title) {
        jXDatePicker1.setDate(new Date());
        ArrayList vendorsList = new ArrayList();
        ArrayList accountsList = DBM.getAllRecords(Account.class);
        switch (title) {
            case "Payable":
                System.out.println("asd");
                vendorsList = DBM.getRecordsBy(Vendors.class, "Type", "Vendor");
                System.out.println(vendorsList.size());
                break;
            case "Receiveable":
                System.out.println("askhf");
                vendorsList = DBM.getRecordsBy(Vendors.class, "Type", "Customer");
                jLabel3.setText("Customer Name");
                jLabel4.setText("Customer Balance");
                break;
        }
        Global.addListToCombo(comboVendorNameAuto, vendorsList);
        Global.addListToCombo(comboPaymentMethod, accountsList);
        AutoCompleteDecorator.decorate(comboVendorNameAuto);
    }
}
