/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ay.isystem.views.panels.vendors;

import com.ay.isystem.models.EntityBeans.Account;
import com.ay.isystem.models.EntityBeans.Vendors;
import com.ay.isystem.utililty.Global;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author java
 */
public class AddPayablesDialog extends javax.swing.JDialog {

    static long paymentId;
    static long getAccountNo;
    static long vendorId;
    JTable jTable;
    int rowId;
    boolean flag = false;
    ArrayList<Vendors> vendorlist;
    ArrayList<Account> Accountlist;
    double preAmount = 0;
    long preAccount = 0;

    Image imageIcon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/pump.png"));

    public AddPayablesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        this.jXDatePicker1.setFormats(dateFormat);
        this.jXDatePicker1.setDate(new Date());
        loadVendorNames();
        loadPaymentMethods();
        this.setIconImage(imageIcon);
    }

    public AddPayablesDialog(java.awt.Frame parent, boolean modal, JTable jTable) {
        super(parent, modal);
        initComponents();
        this.jTable = jTable;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        this.jXDatePicker1.setFormats(dateFormat);
        this.jXDatePicker1.setDate(new Date());
        loadVendorNames();
        loadPaymentMethods();
        this.setIconImage(imageIcon);
    }

    public AddPayablesDialog(java.awt.Frame parent, boolean modal, JTable jTable, int rowId) {
        super(parent, modal);
        initComponents();
        this.jTable = jTable;
        this.rowId = rowId;
        flag = true;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        this.jXDatePicker1.setFormats(dateFormat);
        this.jXDatePicker1.setDate(new Date());
        loadVendorNames();
        loadPaymentMethods();
        this.setIconImage(imageIcon);

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date date = formatter.parse(this.jTable.getValueAt(rowId, 3).toString());
            this.jXDatePicker1.setDate(date);
        } catch (ParseException e) {
        }

        for (Vendors v : vendorlist) {
            if (v != null) {
                if (this.jTable.getValueAt(rowId, 2).toString().equals(v.getName())) {
                    comboVendorNameAuto.setSelectedIndex(vendorlist.indexOf(v));
                }
            }
        }
        comboVendorNameAuto.setEnabled(false);
        for (Account acc : Accountlist) {
            if (acc != null) {
                comboPaymentMethod.setSelectedIndex(Accountlist.indexOf(acc));
                preAccount = acc.getId();
            }
        }

        etAmount.setText(this.jTable.getValueAt(rowId, 6).toString());
        this.preAmount = Double.parseDouble(this.jTable.getValueAt(this.rowId, 6).toString());
        etRemarks.setText(this.jTable.getValueAt(rowId, 7).toString());
        if (!comboPaymentMethod.getSelectedItem().equals("Cash")) {
            txtCheque.setText(this.jTable.getValueAt(rowId, 8).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etRemarks = new javax.swing.JTextField();
        comboVendorNameAuto = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboPaymentMethod = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        etAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        currentBalance = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCheque = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("EXIT");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Date");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Remarks");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Vendor Name");

        comboVendorNameAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVendorNameAutoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Vendor Balance");

        comboPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaymentMethodActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Amount ");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Account ");

        currentBalance.setEditable(false);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Cheque No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboPaymentMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentBalance)
                            .addComponent(comboVendorNameAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCheque)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {etAmount, txtCheque});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboVendorNameAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {etAmount, txtCheque});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void comboVendorNameAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVendorNameAutoActionPerformed
//        DefaultComboBoxModel dfComboModelVendor = (DefaultComboBoxModel) this.comboVendorNameAuto.getModel();
        Vendors vendorBean = (Vendors) this.comboVendorNameAuto.getSelectedItem();
        vendorId = vendorBean.getId();
        currentBalance.setText("" + vendorBean.getCurrentBalance());
    }//GEN-LAST:event_comboVendorNameAutoActionPerformed

    private void comboPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaymentMethodActionPerformed
        DefaultComboBoxModel dfComboModel = (DefaultComboBoxModel) this.comboPaymentMethod.getModel();
        String item = dfComboModel.getSelectedItem().toString();
        if (item.equals("Cash")) {
            jLabel5.setVisible(false);
            txtCheque.setVisible(false);
            txtCheque.setText("");
        } else {
            jLabel5.setVisible(true);
            txtCheque.setVisible(true);
        }
    }//GEN-LAST:event_comboPaymentMethodActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!flag) {
            Date date = jXDatePicker1.getDate();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String formatedDate = simpleDateFormat.format(date);
//            Date calDate = DBManager.calculateDate(formatedDate);
            String payment = this.comboPaymentMethod.getSelectedItem().toString();
            double amount = Double.parseDouble(this.etAmount.getText());
            String remark = this.etRemarks.getText();
            Account bean = (Account) this.comboPaymentMethod.getSelectedItem();
            paymentId = bean.getId();
            System.out.println("paymentId " + paymentId);
            Vendors vendorBean = (Vendors) this.comboVendorNameAuto.getSelectedItem();
            vendorId = vendorBean.getId();
            int chequeNum = 0;
            if (!txtCheque.getText().equals("")) {
                chequeNum = Integer.parseInt(txtCheque.getText());
            }
//            int ip = Payable.insertPayable(jTable, calDate, chequeNum, vendorId, paymentId, amount, remark);
//            if (ip > 0) {
//                DBManager.updateVendorBalance(vendorId, amount, false);
////                if ((int) DBManager.getCashId(true) != paymentId) {
//                DBManager.updateOurBalance(paymentId, amount, 2);
////                }
//            }
            this.dispose();
        } else {

//            Date date = datePicker.getDate();
//            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
//            String formatedDate = simpleDateFormat.format(date);
//            Date calDate = DBManager.calculateDate(formatedDate);
////            String payment = this.comboPaymentMethod.getSelectedItem().toString();
//            double amount = Double.parseDouble(this.etAmount.getText());
//            double diffAmount = amount - this.preAmount;
//            String remark = this.etRemarks.getText();
//            PaymentBean bean = (PaymentBean) this.comboPaymentMethod.getSelectedItem();
//            paymentId = bean.getId();
//            VendorBean vendorBean = (VendorBean) this.comboVendorNameAuto.getSelectedItem();
//            vendorId = vendorBean.getId();
//            int payId = Integer.parseInt(this.jTable.getValueAt(this.rowId, 0).toString());
//            int chequeNum = 0;
//            if (!txtCheque.getText().equals("")) {
//                chequeNum = Integer.parseInt(txtCheque.getText());
//            }
//            int usp = Payable.updatShowPayable(jTable, payId, calDate, chequeNum, vendorId, paymentId, amount, remark);
//            if (usp > 0) {
//                DBManager.updateVendorBalance(vendorId, diffAmount, false);
//                if ((int) DBManager.getCashId(true) != paymentId) {
//                    if (preAccount != paymentId) {
//                        DBManager.updateOurBalance(preAccount, preAmount, 1);
//                        DBManager.updateOurBalance(paymentId, preAmount, 2);
//                    }
//                    DBManager.updateOurBalance(paymentId, diffAmount, 2);
//
//                }
//            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPayablesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddPayablesDialog dialog = new AddPayablesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboPaymentMethod;
    private javax.swing.JComboBox comboVendorNameAuto;
    private javax.swing.JTextField currentBalance;
    private javax.swing.JTextField etAmount;
    private javax.swing.JTextField etRemarks;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField txtCheque;
    // End of variables declaration//GEN-END:variables
final public void loadVendorNames() {
        vendorlist = (ArrayList<Vendors>) Global.CONTROLLER.fetch("vendor").getResponseObject();
        Vendors bean;
        for (Vendors vendorlist1 : vendorlist) {
            bean = vendorlist1;
            this.comboVendorNameAuto.addItem(bean);
        }
        AutoCompleteDecorator.decorate(comboVendorNameAuto);
    }

    final public void loadPaymentMethods() {
        Accountlist = (ArrayList<Account>) Global.CONTROLLER.fetch("account").getResponseObject();
        Account bean;
        for (Account Accountlist1 : Accountlist) {
            bean = Accountlist1;
            this.comboPaymentMethod.addItem(bean);
        }
    }
}
