package com.ay.isystem.views.panels.vendors;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.ay.isystem.models.EntityBeans.Vendors;
import com.ay.isystem.models.Response;
import com.ay.isystem.utililty.Global;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author java
 */
public class AddVendorDialog extends javax.swing.JDialog {

    private Vendors vendor = new Vendors();
    private double lastOpening;
    private double lastCurrentBalance;

    private boolean updateFlag = false;

    public AddVendorDialog(java.awt.Frame parent, boolean modal, String type) {
        super(parent, modal);
        initComponents();
        vendor.setType(type);
        jLabel1.setText(type + " Information");
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    public AddVendorDialog(java.awt.Frame parent, boolean modal, Vendors vendor, JTable jTable) {
        super(parent, modal);
        initComponents();
        updateFlag = true;
        this.vendor = vendor;
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
//        provinceList = DBManager.getProvinces(comboVendorState);
//        cityList = DBManager.getCitiesFromProvince(vendor.getState(), comboVendorCity);
        lastOpening = this.vendor.getOpeningBalance();
        lastCurrentBalance = this.vendor.getCurrentBalance();
//        loadFields(vendor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        etVendorName = new javax.swing.JTextField();
        errName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        errAddress = new javax.swing.JLabel();
        errZipCode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        errProvince = new javax.swing.JLabel();
        errCity = new javax.swing.JLabel();
        errOpenBalance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        errMobile = new javax.swing.JLabel();
        etVendorAddress = new javax.swing.JTextField();
        errPhone = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errEmail = new javax.swing.JLabel();
        etVendorZipCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        etVendorOpeningBalance = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        etVendorMobileNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        etVendorEmail = new javax.swing.JTextField();
        etVendorPhoneNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        errName.setForeground(new java.awt.Color(255, 0, 0));
        errName.setText("  ");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Email");

        errAddress.setForeground(new java.awt.Color(255, 0, 0));
        errAddress.setText("  ");

        errZipCode.setForeground(new java.awt.Color(255, 0, 0));
        errZipCode.setText("  ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendor Information ");

        errProvince.setForeground(new java.awt.Color(255, 0, 0));
        errProvince.setText("  ");

        errCity.setForeground(new java.awt.Color(255, 0, 0));
        errCity.setText("  ");

        errOpenBalance.setForeground(new java.awt.Color(255, 0, 0));
        errOpenBalance.setText("  ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Address");

        errMobile.setForeground(new java.awt.Color(255, 0, 0));
        errMobile.setText("  ");

        errPhone.setForeground(new java.awt.Color(255, 0, 0));
        errPhone.setText("  ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Zip code");

        errEmail.setForeground(new java.awt.Color(255, 0, 0));
        errEmail.setText("  ");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Opening Balance");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Mobile");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errCity)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etVendorZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etVendorAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etVendorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errProvince, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errZipCode, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etVendorPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etVendorMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etVendorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etVendorOpeningBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errMobile)
                            .addComponent(errPhone)
                            .addComponent(errEmail)
                            .addComponent(errOpenBalance))))
                .addGap(30, 30, 30))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {etVendorAddress, etVendorEmail, etVendorMobileNo, etVendorName, etVendorOpeningBalance, etVendorPhoneNo, etVendorZipCode});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, 0)
                        .addComponent(errName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etVendorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, 0)
                        .addComponent(errAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(etVendorZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(errZipCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(9, 9, 9)
                        .addComponent(errProvince))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etVendorOpeningBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, 0)
                        .addComponent(errOpenBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(etVendorMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(errMobile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(etVendorPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(errPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etVendorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(errEmail)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(errCity))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {etVendorAddress, etVendorEmail, etVendorMobileNo, etVendorName, etVendorOpeningBalance, etVendorPhoneNo, etVendorZipCode});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            vendor.setName(etVendorName.getText());
            vendor.setAddress(etVendorAddress.getText());
            vendor.setZipCode(etVendorZipCode.getText());
            vendor.setOpeningBalance(Double.parseDouble(etVendorOpeningBalance.getText()));
            vendor.setCurrentBalance(Double.parseDouble(etVendorOpeningBalance.getText()));
            vendor.setContactPhone(etVendorMobileNo.getText());
            vendor.setTelephone(etVendorPhoneNo.getText());
            vendor.setContactEmail(etVendorEmail.getText());
            Response insertRecord = Global.CONTROLLER.insertRecord(vendor, "Vendors");
            if (insertRecord.isError()) {
                JOptionPane.showMessageDialog(this, insertRecord.getErrorMsg());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
        }

        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel errAddress;
    private javax.swing.JLabel errCity;
    private javax.swing.JLabel errEmail;
    private javax.swing.JLabel errMobile;
    private javax.swing.JLabel errName;
    private javax.swing.JLabel errOpenBalance;
    private javax.swing.JLabel errPhone;
    private javax.swing.JLabel errProvince;
    private javax.swing.JLabel errZipCode;
    private javax.swing.JTextField etVendorAddress;
    private javax.swing.JTextField etVendorEmail;
    private javax.swing.JTextField etVendorMobileNo;
    private javax.swing.JTextField etVendorName;
    private javax.swing.JTextField etVendorOpeningBalance;
    private javax.swing.JTextField etVendorPhoneNo;
    private javax.swing.JTextField etVendorZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
// private void loadFields(VendorBean v) {
//        etVendorName.setText(v.getName());
//        etVendorAddress.setText(v.getAddress());
//        etVendorZipCode.setText(v.getZipCode());
//        etVendorOpeningBalance.setText("" + v.getOpeningBalance());
//        etVendorMobileNo.setText(v.getContactPhone());
//        etVendorPhoneNo.setText(v.getTelephone());
//        etVendorEmail.setText(v.getContactEmail());
//        nameFlag = MainFrame.validate.validateEmpty(etVendorName, strName, errName);
//        addressFlag = MainFrame.validate.validateEmpty(etVendorAddress, strAddress, errAddress);
//        zipCodeFlag = MainFrame.validate.validateZipCode(etVendorZipCode, strZipCode, errZipCode);
//        cityFlag = MainFrame.validate.validateCombo(comboVendorCity, strCity, errCity);
//        openBalanceFlag = MainFrame.validate.validateAmount(etVendorOpeningBalance, strOpenBalance, errOpenBalance);
//        mobileFlag = MainFrame.validate.validatePhnNumber(etVendorMobileNo, strMobile, errMobile);
//        phoneFlag = MainFrame.validate.validatePhnNumber(etVendorPhoneNo, strPhone, errPhone);
//        emailFlag = MainFrame.validate.validateEmail(etVendorEmail, strEmail, errEmail);
//
//        for (int i = 0; i < provinceList.size(); i++) {
//            if (provinceList.get(i).getId() == vendor.getState()) {
//                comboVendorState.setSelectedIndex(i + 1);
//            }
//        }
//        for (int i = 0; i < cityList.size(); i++) {
//            if (cityList.get(i).getId() == vendor.getCity()) {
//                comboVendorCity.setSelectedIndex(i + 1);
//            }
//        }
//
//    }
}
